/*******************************************************************************
 * Copyright (c) 2011 University of Bayreuth - BayCEER.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 * 
 * Contributors:
 *     University of Bayreuth - BayCEER - initial API and implementation
 ******************************************************************************/
/*
 * JPanelTime.java
 *
 * Created on 10. Mai 2004, 11:09
 */

package de.unibayreuth.bayeos.goat.filter;

import javax.swing.JLabel;

import de.unibayreuth.bayceer.bayeos.xmlrpc.filter.TimeFilter;
import de.unibayreuth.bayeos.utils.date.JDefaultDateSpinner;

/**
 *
 * @author  oliver
 */
public class JPanelVonBis extends javax.swing.JPanel {
    
    private JDefaultDateSpinner jSpinnerStart;
    private JDefaultDateSpinner jSpinnerEnd;
    
    private TimeFilter filter;
    
    /** Creates new form JPanelTime */
    
    
    public JPanelVonBis(TimeFilter value) {
        this.filter = value;
        initComponents();
        jSpinnerStart = new JDefaultDateSpinner();               
        jSpinnerStart.setDate(filter.getVon());

        jSpinnerEnd = new JDefaultDateSpinner();           
        jSpinnerEnd.setDate(filter.getBis());
        add(new JLabel(" Start: "));
        add(jSpinnerStart);
        add(new JLabel(" End: "));
        add(jSpinnerEnd);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

    }//GEN-END:initComponents
    
    /**
     * Getter for property filter.
     * @return Value of property filter.
     */
    public TimeFilter getFilter()  {
        this.filter.setVon(jSpinnerStart.getDate());
        this.filter.setBis(jSpinnerEnd.getDate());
        return this.filter;
    }    
    
    /**
     * Setter for property filter.
     * @param filter New value of property filter.
     */
    public void setFilter(TimeFilter value) {
        this.filter = value;
        java.util.Date von = value.getVon();
        java.util.Date bis = value.getBis();
        jSpinnerStart.setDate(von);
        jSpinnerEnd.setDate(bis);
    }
    
    /**
     * Getter for property jSpinnerStart.
     * @return Value of property jSpinnerStart.
     */
    public JDefaultDateSpinner getJSpinnerStart() {
        return jSpinnerStart;
    }
    
    /**
     * Setter for property jSpinnerStart.
     * @param jSpinnerStart New value of property jSpinnerStart.
     */
    public void setJSpinnerStart(JDefaultDateSpinner jSpinnerStart) {
        this.jSpinnerStart = jSpinnerStart;
    }
    
    /**
     * Getter for property jSpinnerEnd.
     * @return Value of property jSpinnerEnd.
     */
    public JDefaultDateSpinner getJSpinnerEnd() {
        return jSpinnerEnd;
    }
    
    /**
     * Setter for property jSpinnerEnd.
     * @param jSpinnerEnd New value of property jSpinnerEnd.
     */
    public void setJSpinnerEnd(JDefaultDateSpinner jSpinnerEnd) {
        this.jSpinnerEnd = jSpinnerEnd;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
