/*******************************************************************************
 * Copyright (c) 2011 University of Bayreuth - BayCEER.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 * 
 * Contributors:
 *     University of Bayreuth - BayCEER - initial API and implementation
 ******************************************************************************/
/*
 * JTest.java
 *
 * Created on 15. Dezember 2003, 10:50
 */

package de.unibayreuth.bayeos.utils.date;

import java.awt.BorderLayout;

import javax.swing.JButton;

/**
 *
 * @author  oliver
 */
public class JDateChangedTest extends javax.swing.JFrame {
    
    private JDefaultDateSpinner t1;
    private JDefaultDateSpinner t2;
        
    /** Creates new form JTest */
    public JDateChangedTest() {
        initComponents();
        getContentPane().setLayout(new BorderLayout());
        t1 = new JDefaultDateSpinner();
        t2 = new JDefaultDateSpinner();
        
        getContentPane().add(t1,BorderLayout.NORTH);
        getContentPane().add(t2,BorderLayout.CENTER);
        getContentPane().add(new JButton("Close"),BorderLayout.SOUTH);
        DateChangedListener u = new JDateChangedTest.UpdateListener();
        t1.addDateChangedListener(u);
        t2.addDateChangedListener(u);
        pack();
    }
    
    
    private class UpdateListener implements DateChangedListener {
        public void changed(DateChangedEvent evt) {
            System.out.println("" + ((JDefaultDateSpinner)evt.getSource()).getDate());
        }
        
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new JDateChangedTest().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
